# Generated by Django 2.2 on 2022-01-10 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('desc', models.CharField(max_length=150)),
                ('body', models.TextField(max_length=5000)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='author.Author')),
            ],
        ),
    ]
