# Generated by Django 2.2 on 2021-12-21 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211220_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='auther',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='author.Author'),
        ),
    ]
